// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: state-grpc.proto

package state

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	StateType     StateType              `protobuf:"varint,2,opt,name=StateType,proto3,enum=state.StateType" json:"StateType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateQuery) Reset() {
	*x = StateQuery{}
	mi := &file_state_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateQuery) ProtoMessage() {}

func (x *StateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_state_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateQuery.ProtoReflect.Descriptor instead.
func (*StateQuery) Descriptor() ([]byte, []int) {
	return file_state_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *StateQuery) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *StateQuery) GetStateType() StateType {
	if x != nil {
		return x.StateType
	}
	return StateType_NOT_USED
}

var File_state_grpc_proto protoreflect.FileDescriptor

const file_state_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10state-grpc.proto\x12\x05state\x1a\x1bgoogle/protobuf/empty.proto\x1a\vstate.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"i\n" +
	"\n" +
	"StateQuery\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12.\n" +
	"\tStateType\x18\x02 \x01(\x0e2\x10.state.StateTypeR\tStateType2f\n" +
	"\fStateService\x12.\n" +
	"\x06Upsert\x12\f.state.State\x1a\x16.google.protobuf.Empty\x12&\n" +
	"\x03Get\x12\x11.state.StateQuery\x1a\f.state.StateB/Z-github.com/sologenic/com-fs-state-model;stateb\x06proto3"

var (
	file_state_grpc_proto_rawDescOnce sync.Once
	file_state_grpc_proto_rawDescData []byte
)

func file_state_grpc_proto_rawDescGZIP() []byte {
	file_state_grpc_proto_rawDescOnce.Do(func() {
		file_state_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_grpc_proto_rawDesc), len(file_state_grpc_proto_rawDesc)))
	})
	return file_state_grpc_proto_rawDescData
}

var file_state_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_grpc_proto_goTypes = []any{
	(*StateQuery)(nil),    // 0: state.StateQuery
	(metadata.Network)(0), // 1: metadata.Network
	(StateType)(0),        // 2: state.StateType
	(*State)(nil),         // 3: state.State
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_state_grpc_proto_depIdxs = []int32{
	1, // 0: state.StateQuery.Network:type_name -> metadata.Network
	2, // 1: state.StateQuery.StateType:type_name -> state.StateType
	3, // 2: state.StateService.Upsert:input_type -> state.State
	0, // 3: state.StateService.Get:input_type -> state.StateQuery
	4, // 4: state.StateService.Upsert:output_type -> google.protobuf.Empty
	3, // 5: state.StateService.Get:output_type -> state.State
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_grpc_proto_init() }
func file_state_grpc_proto_init() {
	if File_state_grpc_proto != nil {
		return
	}
	file_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_grpc_proto_rawDesc), len(file_state_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_grpc_proto_goTypes,
		DependencyIndexes: file_state_grpc_proto_depIdxs,
		MessageInfos:      file_state_grpc_proto_msgTypes,
	}.Build()
	File_state_grpc_proto = out.File
	file_state_grpc_proto_goTypes = nil
	file_state_grpc_proto_depIdxs = nil
}
