// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: state.proto

package state

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateType int32

const (
	StateType_NOT_USED                       StateType = 0
	StateType_ORDER_PURCHASE_LISTENER        StateType = 1
	StateType_ORDER_SELL_LISTENER            StateType = 2
	StateType_ORDER_CANCEL_REQUEST_LISTENER  StateType = 3
	StateType_ORDER_UPDATE_LISTENER          StateType = 4 // Order Execution
	StateType_ORDER_PAY_LISTENER             StateType = 5
	StateType_REATTESTATION_REQUEST_LISTENER StateType = 6
	StateType_PUB_SUB                        StateType = 7
	StateType_ORDER_PASS_LISTENER            StateType = 8
)

// Enum value maps for StateType.
var (
	StateType_name = map[int32]string{
		0: "NOT_USED",
		1: "ORDER_PURCHASE_LISTENER",
		2: "ORDER_SELL_LISTENER",
		3: "ORDER_CANCEL_REQUEST_LISTENER",
		4: "ORDER_UPDATE_LISTENER",
		5: "ORDER_PAY_LISTENER",
		6: "REATTESTATION_REQUEST_LISTENER",
		7: "PUB_SUB",
		8: "ORDER_PASS_LISTENER",
	}
	StateType_value = map[string]int32{
		"NOT_USED":                       0,
		"ORDER_PURCHASE_LISTENER":        1,
		"ORDER_SELL_LISTENER":            2,
		"ORDER_CANCEL_REQUEST_LISTENER":  3,
		"ORDER_UPDATE_LISTENER":          4,
		"ORDER_PAY_LISTENER":             5,
		"REATTESTATION_REQUEST_LISTENER": 6,
		"PUB_SUB":                        7,
		"ORDER_PASS_LISTENER":            8,
	}
)

func (x StateType) Enum() *StateType {
	p := new(StateType)
	*p = x
	return p
}

func (x StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (StateType) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateType.Descriptor instead.
func (StateType) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateType     StateType              `protobuf:"varint,1,opt,name=StateType,proto3,enum=state.StateType" json:"StateType,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	MetaData      *metadata.MetaData     `protobuf:"bytes,3,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetStateType() StateType {
	if x != nil {
		return x.StateType
	}
	return StateType_NOT_USED
}

func (x *State) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *State) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x05state\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\x81\x01\n" +
	"\x05State\x12.\n" +
	"\tStateType\x18\x01 \x01(\x0e2\x10.state.StateTypeR\tStateType\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12.\n" +
	"\bMetaData\x18\x03 \x01(\v2\x12.metadata.MetaDataR\bMetaData*\xef\x01\n" +
	"\tStateType\x12\f\n" +
	"\bNOT_USED\x10\x00\x12\x1b\n" +
	"\x17ORDER_PURCHASE_LISTENER\x10\x01\x12\x17\n" +
	"\x13ORDER_SELL_LISTENER\x10\x02\x12!\n" +
	"\x1dORDER_CANCEL_REQUEST_LISTENER\x10\x03\x12\x19\n" +
	"\x15ORDER_UPDATE_LISTENER\x10\x04\x12\x16\n" +
	"\x12ORDER_PAY_LISTENER\x10\x05\x12\"\n" +
	"\x1eREATTESTATION_REQUEST_LISTENER\x10\x06\x12\v\n" +
	"\aPUB_SUB\x10\a\x12\x17\n" +
	"\x13ORDER_PASS_LISTENER\x10\bB/Z-github.com/sologenic/com-fs-state-model;stateb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_proto_goTypes = []any{
	(StateType)(0),            // 0: state.StateType
	(*State)(nil),             // 1: state.State
	(*metadata.MetaData)(nil), // 2: metadata.MetaData
}
var file_state_proto_depIdxs = []int32{
	0, // 0: state.State.StateType:type_name -> state.StateType
	2, // 1: state.State.MetaData:type_name -> metadata.MetaData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
